const WORKSPACE_COLLECTIONS = Object.freeze([
  ['analytics', require('../models/Analytics')],
  ['apiTokens', require('../models/ApiToken')],
  ['approvals', require('../models/Approval')],
  ['auditEvents', require('../models/AuditEvent')],
  ['boardHealthSnapshots', require('../models/BoardHealthSnapshot')],
  ['boards', require('../models/Board')],
  ['capacityProfiles', require('../models/CapacityProfile')],
  ['cardFindings', require('../models/CardFinding')],
  ['cards', require('../models/Card')],
  ['comments', require('../models/Comment')],
  ['connectorAccounts', require('../models/ConnectorAccount')],
  ['conversations', require('../models/Conversation')],
  ['decisionQueueItems', require('../models/DecisionQueueItem')],
  ['featureFlags', require('../models/FeatureFlag')],
  ['followUpPlans', require('../models/FollowUpPlan')],
  ['interventions', require('../models/Intervention')],
  ['jobControls', require('../models/JobControl')],
  ['jobRuns', require('../models/JobRun')],
  ['learningRecords', require('../models/Learning')],
  ['lists', require('../models/List')],
  ['members', require('../models/Member')],
  ['notificationDeliveries', require('../models/NotificationDelivery')],
  ['notificationPolicies', require('../models/NotificationPolicy')],
  ['outcomeRecords', require('../models/OutcomeRecord')],
  ['performanceRecords', require('../models/Performance')],
  ['policyRules', require('../models/PolicyRule')],
  ['recommendations', require('../models/Recommendation')],
  ['sessionTokens', require('../models/SessionToken')],
  ['trelloActionAttempts', require('../models/TrelloActionAttempt')],
  ['users', require('../models/User')],
  ['webhookDeliveries', require('../models/WebhookDelivery')],
  ['workActors', require('../models/WorkActor')],
  ['workComments', require('../models/WorkComment')],
  ['workContainers', require('../models/WorkContainer')],
  ['workDependencies', require('../models/WorkDependency')],
  ['workerResponses', require('../models/WorkerResponse')],
  ['workEvents', require('../models/WorkEvent')],
  ['workItems', require('../models/WorkItem')],
  ['workSignals', require('../models/WorkSignal')],
  ['workspaceInvitations', require('../models/WorkspaceInvite')]
]);

module.exports = { WORKSPACE_COLLECTIONS };
